# Doc2Any Blog - Simple Docker Compose (without Traefik)
# Perfect for Apache2 reverse proxy setups
# Use: docker compose -f docker-compose.simple.yml up -d
version: '3.8'

services:
  # Main application
  doc2any-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc2any-blog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_GA_ID=UA-47319849-1
      - NEXT_PUBLIC_ADSENSE_CLIENT=ca-pub-2591708616273466
    restart: unless-stopped
    networks:
      - doc2any-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: doc2any-redis
    restart: unless-stopped
    networks:
      - doc2any-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: doc2any-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - doc2any-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # Grafana for metrics visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: doc2any-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - doc2any-network

networks:
  doc2any-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data:
